cluster:
  sbatch
    --partition={resources.slurm_partition}
    --cpus-per-task={resources.cpu_per_task}
    --mem={resources.mem_mb}
    --ntasks={resources.tasks}
    --nodes=1
    --job-name={resources.jobname}
    --account=mps_chrom_cp_nb
default-resources:
  - partition=fast
  - account=mps_chrom_cp_nb
  - mem_mb=100000
  - cpu_per_task=8
  
restart-times: 1
latency-wait: 60
jobs: 10
keep-going: True
rerun-incomplete: True
use-conda: True